# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoPlayer = VideoPlayer(self.centralwidget)
        self.videoPlayer.setGeometry(QtCore.QRect(310, 20, 679, 247))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        self.videoPlayer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.videoPlayer.setStyleSheet("border: 1px solid black;\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.videoPlayer.setObjectName("videoPlayer")
        self.movieDetailTableView = QtWidgets.QTableView(self.centralwidget)
        self.movieDetailTableView.setGeometry(QtCore.QRect(20, 10, 251, 451))
        self.movieDetailTableView.setMinimumSize(QtCore.QSize(0, 200))
        self.movieDetailTableView.setObjectName("movieDetailTableView")
        self.mainProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.mainProgressBar.setGeometry(QtCore.QRect(300, 350, 681, 23))
        self.mainProgressBar.setProperty("value", 0)
        self.mainProgressBar.setObjectName("mainProgressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 600, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 600, 231, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.ffmpegAddressBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ffmpegAddressBtn.setGeometry(QtCore.QRect(430, 600, 75, 23))
        self.ffmpegAddressBtn.setObjectName("ffmpegAddressBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 640, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 640, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.videoAddressBtn = QtWidgets.QPushButton(self.centralwidget)
        self.videoAddressBtn.setGeometry(QtCore.QRect(430, 640, 75, 23))
        self.videoAddressBtn.setObjectName("videoAddressBtn")
        self.startProcessBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startProcessBtn.setGeometry(QtCore.QRect(430, 690, 75, 23))
        self.startProcessBtn.setObjectName("startProcessBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.ffmpegAddressBtn.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.videoAddressBtn.setText(_translate("MainWindow", "PushButton"))
        self.startProcessBtn.setText(_translate("MainWindow", "PushButton"))
from py.VideoPlayer import VideoPlayer
