# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 410, 351, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leVideoFileAddress = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.leVideoFileAddress.setObjectName("leVideoFileAddress")
        self.horizontalLayout.addWidget(self.leVideoFileAddress)
        self.pbChooseVideoFile = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbChooseVideoFile.setObjectName("pbChooseVideoFile")
        self.horizontalLayout.addWidget(self.pbChooseVideoFile)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slSceneSensitivity = QtWidgets.QSlider(self.formLayoutWidget)
        self.slSceneSensitivity.setMaximum(100)
        self.slSceneSensitivity.setSingleStep(1)
        self.slSceneSensitivity.setProperty("value", 20)
        self.slSceneSensitivity.setOrientation(QtCore.Qt.Horizontal)
        self.slSceneSensitivity.setObjectName("slSceneSensitivity")
        self.horizontalLayout_2.addWidget(self.slSceneSensitivity)
        self.lbSceneSensitivity = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbSceneSensitivity.setObjectName("lbSceneSensitivity")
        self.horizontalLayout_2.addWidget(self.lbSceneSensitivity)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 631, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wdVideo = QtWidgets.QWidget(self.centralwidget)
        self.wdVideo.setGeometry(QtCore.QRect(470, 280, 281, 271))
        self.wdVideo.setObjectName("wdVideo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Scene Sensitivity"))
        self.label_2.setText(_translate("MainWindow", "Video Address"))
        self.pbChooseVideoFile.setText(_translate("MainWindow", "Open"))
        self.lbSceneSensitivity.setText(_translate("MainWindow", "20%"))
